# Generated by Django 4.2.19 on 2025-03-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
