# Generated by Django 4.2.19 on 2025-03-30 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='on_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 20, 45, 59, 901521)),
        ),
        migrations.AddField(
            model_name='borrow',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
