# Generated by Django 4.2.19 on 2025-03-30 20:49

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_borrow_borrow_date_borrow_is_overdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=products.models.default_return_date),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
