# Generated by Django 4.2.20 on 2025-03-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='collection_name',
        ),
    ]
