# Generated by Django 4.2.20 on 2025-03-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_name_collection_collection_name'),
        ('products', '0007_product_is_available'),
    ]

    operations = [
    ]
