# Generated by Django 4.2.20 on 2025-04-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20250331_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='visible_to',
        ),
    ]
