# Generated by Django 4.2.20 on 2025-04-14 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='visibility_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
