# Generated by Django 4.2.19 on 2025-04-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20250331_2059'),
        ('products', '0010_review'),
    ]

    operations = [
    ]
