# Generated by Django 4.2.20 on 2025-04-14 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_collection_visibility_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
