# Generated by Django 4.2.19 on 2025-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_borrow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='on_rent',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('On Rent', 'On Rent'), ('Returned', 'Returned')], default='Pending', max_length=10),
        ),
    ]
