# Generated by Django 4.2.19 on 2025-04-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_collection_visible_to'),
        ('products', '0013_remove_borrow_is_returned_remove_borrow_on_rent_and_more'),
    ]

    operations = [
    ]
