# Generated by Django 4.2.19 on 2025-04-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_collection_visible_to'),
        ('products', '0014_product_is_repairing'),
    ]

    operations = [
    ]
