# Generated by Django 4.2.19 on 2025-04-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20250414_0352'),
        ('products', '0015_merge_20250414_0343'),
    ]

    operations = [
    ]
