# Generated by Django 4.2.20 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_merge_20250414_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_private_collection',
            field=models.BooleanField(default=False),
        ),
    ]
