# Generated by Django 4.2.19 on 2025-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_merge_20250414_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Library', max_length=100),
        ),
    ]
