# Generated by Django 4.2.20 on 2025-04-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_category_product_location'),
        ('products', '0017_product_in_private_collection'),
    ]

    operations = [
    ]
